//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentApp
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class student
    {
        public student ()
        {

        }

        public student(int nextStudentID, string firstNameCaseCorrect, string lastNameCaseCorrect, int currentCreditsNumeric, int totalCreditsNumeric)
        {
            Id = nextStudentID;
            StudentFirstName = firstNameCaseCorrect;
            StudentLastName = lastNameCaseCorrect;
            CurrentCredits = currentCreditsNumeric;
            TotalCredits = totalCreditsNumeric;
        }

        public int Id { get; set; }
        public string StudentLastName { get; set; }
        public string StudentFirstName { get; set; }
        public int CurrentCredits { get; set; }
        public int TotalCredits { get; set; }

        public string FullName
        {
            get
            {
                return $"{StudentFirstName} {StudentLastName}";
            }
        }

        // adds current credits to total credits then sets current credits to 0
        public void AddCurrentToTotal()
        {
            TotalCredits += CurrentCredits;
            CurrentCredits = 0;
        }
    }
}
